name: Terraform CD
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to apply'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - run: terraform init
        working-directory: ./terraform

      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: terraform_ci.yml
          name: tfplan-${{ github.event.inputs.commit_sha }}
          path: ./terraform

      - run: terraform apply -auto-approve tfplan.binary
        working-directory: ./terraform